# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0
#
# Operating Modes:
#    1 = current control
#    2 = speed control
#    3 = position control
#    4 = multi-turn position control
#    5 = position + current control
#   16 = direct voltage control
#

# Left finger
left_finger_top:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 5 
  Profile_Acceleration: 0
  Profile_Velocity: 0

left_finger_bottom:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0

left_finger_cable:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0

# Right finger
right_finger_top:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0

right_finger_bottom:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0

right_finger_cable:
  ID: 6
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
